import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "./navigation/NavigationBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        style={{
          margin: 0,
          background: "#121212",
          color: "#e0e0e0",
          fontFamily: "sans-serif",
        }}
      >
        <NavigationBar />
        <main
          style={{
            maxWidth: "100%",
            margin: "0 auto",
            padding: 32,
          }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
